# Generated by Django 6.0.1 on 2026-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_restaurantmenuitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_master_food',
            field=models.BooleanField(default=False),
        ),
    ]
