# Generated by Django 6.0.1 on 2026-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_food_is_master_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
